platform:
  - x86
  - x64

environment:
  matrix:
    - PHP_VERSION: 7.0
    - PHP_VERSION: 7.1

services:
  - mysql
  - postgresql

init:
  - SET DUNCAN3DC_CACHE=c:\duncan3dc
  - SET PATH=C:\Program Files\MySQL\MySQL Server 5.7\bin\;C:\Program Files\PostgreSQL\9.6\bin\;%PATH%;
  - SET MYSQL_PASSWORD=Password12!
  - SET POSTGRES_PASSWORD=Password12!

cache:
  - '%DUNCAN3DC_CACHE%'

install:
  - appveyor DownloadFile https://raw.githubusercontent.com/duncan3dc/appveyor/master/php.ps1
  - ps: .\php.ps1

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - vendor\bin\phpunit

build: false
clone_depth: 5
