language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  global:
    - POSTGRES_PASSWORD=""
  matrix:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update --snapshot
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit --coverage-clover=clover.xml
  - tests/lint.sh

after_success:
  - vendor/bin/coveralls

services:
  - mysql
  - postgresql

git:
  depth: 5

dist: trusty
sudo: false
